### ISSUE TITLE
Cyclic Anti-Gravity Ring

### ISSUE THREAD

**Issue by BangRocket** [BangRocket/StoneIndustriesPack#2]
Cyclic contains an item called "Anti-Gravity Ring" that allows creative-style flight, with wear.

**Comment by StardustOfficial** [comment]
nope
just tested, pushes you up and down a block when you press space/shift and is very slow compared to creative flight with none of the 'drift' you get when releasing keys, more like a knockoff creative flight that isn't really flight, just walking on air as it says

**Comment by BangRocket** [comment]
Sounds good. Item requirements are within balance then. Guess I'm just dumb. Thanks for confirming.
